### ISSUE TITLE
Project Storyboard : Transition from TD to VS Step 0

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/try#110]
In our Product Roadmap, we explored the theme "smooth transition" -working locally. As steps towards this experience, we will be adding a temp VS banner to the TDN experience when the user hits run.
**Please Note:**  _This is just the first iteration of the experience will change overtime._

| Icon          | Description   |
| ------------- | ------------- |
| Completed     | Check mark    |
| Not Started   | No check      |
| In progress   | :hammer:      |
| Stretch goal  | :tophat:      |

**Operations** 
--
- [X] [Setting up a tailored install experience ](https://github.com/dotnet/try/issues/111)
- [X] [Thank you page](https://github.com/dotnet/try/issues/111)
- [X] [Setting up the tracking URL specific to TDN](https://github.com/dotnet/try/issues/111)
- [ ]  [Measuring users interactions : Did the user click or dismiss the banner?
](https://github.com/dotnet/try/issues/112)  
- [ ] [Testing paper mock-ups options 1 & 2 with partners](https://github.com/dotnet/try/issues/113)
- [ ]  [A/B Testing UX   ](https://github.com/dotnet/try/issues/113)

**Experience**
--
The ones listed below are just the two we are going to start with and test with customers and partners.
- [ ] [Banner is only displayed to user who don't have VS installed ](https://github.com/dotnet/try/issues/100)
- **Option 1** :  [VS Banner Closed  ](https://github.com/dotnet/try/issues/116)
![closes](https://user-images.githubusercontent.com/2546640/42644696-37ce5ae2-85ca-11e8-9e16-de43ca06364d.gif)
  - [X] Use is only presented with the banner after the run the code.
  - [X] User can easily close the banner
     - [X] If the user clicks on the banner they are redirected to the download page
  - [X] The banner is **only** displayed the user **once**. 
-  **Option 2** : [VS Banner minimized ](https://github.com/dotnet/try/issues/115)
![minime](https://user-images.githubusercontent.com/2546640/42646555-382e89bc-85cf-11e8-9239-d20c67aeb0f1.gif)

   - [X] User is only presented with the banner after the run the code
   - [X] User can easily minimized the banner
       - [X] :tophat: Mini-minimized menu appears in the next snippet the user runs.
       - [X] If the user clicks on the banner they are redirected to the download page
-  [ ] :tophat:  Customizing Experience 
        - [ ] Host can customize their banner color.

-  **New ** :  [Option 3 - VS download dismissed - PC & Mac](https://github.com/dotnet/try/issues/126)
 - [X] User starts one of the Quick Starts
<img width="700" alt="vs1" src="https://user-images.githubusercontent.com/2546640/42779841-97d67030-890f-11e8-9815-9c73f76a7d6b.PNG">

- [X] User hits the run button 
<img width="700" alt="vs2" src="https://user-images.githubusercontent.com/2546640/42779963-eeda45d2-890f-11e8-85a6-2e3a0ea8e3f7.PNG">

- [X] "Banner" appears; notifying that user they can download Visual Studio
<img width="700" alt="vs3" src="https://user-images.githubusercontent.com/2546640/42780047-2af5468e-8910-11e8-9a4a-00014bc7bef9.PNG">

- [X] User can minimize the "banner".
<img width="700" alt="vs34png" src="https://user-images.githubusercontent.com/2546640/42780093-5d71d212-8910-11e8-8c78-860eacdbe6c4.PNG">

- [X]  VS Icon remains as a minimized menu
<img width="700" alt="vs5png" src="https://user-images.githubusercontent.com/2546640/42780195-947acf66-8910-11e8-96bf-4497a3e12741.PNG">

- [X]  User continues to next step . The minimized menu still appears in the lower right corner on editor window.
<img width="700" alt="vs6png" src="https://user-images.githubusercontent.com/2546640/42780296-ceb5a340-8910-11e8-888d-2d317af4bb48.PNG">

- [ ] User can click on the VS Icon to reveal the full "banner".
<img width="700" alt="vs7" src="https://user-images.githubusercontent.com/2546640/42780359-fdbfe6b4-8910-11e8-8822-72645bca7a24.PNG">

- [ ] full "banner" reappears.
<img width="700" alt="vs8" src="https://user-images.githubusercontent.com/2546640/42780440-277c195a-8911-11e8-9204-f38b1df4fbdb.PNG">

- [ ] User clicks on work locally to prompt download
<img width="899" alt="vs9" src="https://user-images.githubusercontent.com/2546640/42780538-78eb3208-8911-11e8-9ce9-cb0f631b4f1f.PNG">

**Comment by akshita31** [comment]
Should we trigger the download for the user or just redirect them to a downloads page. Is just clicking the message "Get Started With Visual Studio" a signal that the user wants us to do a download for them.

Also, will our assessment metric be just - The number of downloads we triggered or should it be the number of people who actually click the Run button and installed Visual Studio ?

**Comment by LadyNaggaga** [comment]
@akshita31 Really good questions. Answers below 

- Should we trigger the download for the user or just redirect them to a downloads page? 
  - The redirect link will also trigger a download that the user needs to accept.
- Also, will our assessment metric be just - The number of downloads we triggered or should it be the number of people who actually click the Run button and install Visual Studio ?
   - The number of people who click the run button and install VS .  Since they will only see the VS banner  after they hit the run button.

**Comment by shanselman** [comment]
I love this idea but I there are a few technical issues that will prevent us from really nailed it. No worries, we can still have the "Press Run and see the banner."

* There's no public API (yet) for getting a list of apps to detect if VS is installed. The GetInstalledRelatedApps API is still Chrome-only and I believe it's behind a Chrome:Flag for now AND it's meant for mobile apps. AFAIK. I could be wrong.

* We should likely avoid cookies and/or explore localStorage (can we avoid GDPR with localstorage?) for the "opt-out?"

Either way, the general idea of "click run and THEN show the banner" is great. I love the purple. 

Not sure about the text...I'd use something more ACTION oriented. Get Started seems passive. Maybe:

* Continue learning locally with Visual Studio...
* Download and work locally with Visual Studio...

**Comment by akshita31** [comment]
For Ubuntu we will show the link "Work locally with Visual Studio Code". However Visual Studio Code is not a full fledged IDE, it is more of an editor and to enable the C# capabillities we need to download the C# extension separately. So, is it fair to link the user from try.dot.net to an editor which by default does not have the C# support ?

**Comment by akshita31** [comment]
When we display the banner, if the user clicked on it and downloaded Visual Studio, the next time they open the tutorial, they will again be prompted to download Visual Studio. Won't that experience be annoying?
Is it possible to have some notion of state here, like this user has already downloaded the previous time, so no need to show the banner now.

**Comment by dend** [comment]
As we discussed on the call, we should investigate how we can potentially A/B test the string, to see what resonates better with the users.
