### ISSUE TITLE
Experimenting with Blazor 

### ISSUE THREAD

**Issue by LadyNaggaga** [dotnet/try#97]
Suggestion from @jskeet and @jongalloway 
cc'd: @jonsequitur 
Reference:  [Product Roadmap Review ](https://github.com/dotnet/try/issues/90)
Areas to explore 
- [x] Clients side execution 
- [ ] Using Blazor potentially removes all of the security/provisioning/onboarding aspects, which would be wonderful.
- [ ] Using Blazor would also allow offline experimentation (on a plane!) and potentially be more responsive. Really looking forward to this.

**Comment by LadyNaggaga** [comment]
@danroth27  JFYI  on some of the conversation we are having around Blazor.

**Comment by danroth27** [comment]
Some folks in the community have managed to get Roslyn running in the browser on Blazor: https://github.com/Suchiman/Runny. It works, but it's very slow, probably because Blazor currently is running on an unoptimized IL interpreter. We're working with the mono folks to address Blazor perf, but it may be some time (months?) before we've got it resolved.

**Comment by jongalloway** [comment]
Even if it's slow, I think it would be good to start with something that offers a try.net experience using Blazor + other try.net features (e.g. code editing, loading from gist). Reasons:
 1. The speed or experience may still be better in some circumstances, e.g. on a plane, conference workshop with poor wi-fi, parts of the world with poor internet.
 1. It'd be great to have this be a central area for the community to pitch in as Blazor perf improves. Otherwise, we'll end up with a situation where a community member launches the first one and we're left with difficult choices of having a fractured experience or competing with them. Who knows, we could get the Ben Adams effect here. ;-)

**Comment by LadyNaggaga** [comment]
@jonsequitur  and @TheRealPiotrP  thoughts on the above. I think it's worth us doing group hackathon to try this out

**Comment by jonsequitur** [comment]
Absolutely agreed. 

I wonder if there might be a hybrid approach that doesn't have to wait on Blazor performance (and we're happy to be early adopters). Could the browser submit code to be compiled on the server and the  resulting assembly be sent back for execution in the browser? Try .NET already does compilation for code completion and signature help, which scale well, so we don't necessarily need Blazor there. The more immediate problem Blazor would solve for us is exactly as @jskeet pointed out: in-browser execution would remove the security concern which is our main scale bottleneck and biggest cost. 

This doesn't shift Try .NET entirely to the browser. (For example, full-fidelity ASP.NET samples need Kestrel and will still need to execute on the server.) @jongalloway, this is why our discussions around Try .NET for classrooms with poor internet, workshops, etc. still include running our agent on one machine on the local network, which other machines, including phones, can connect to.
